//
//  bestAcneProducts.swift
//  GlowyFinalProject
//
//  Created by Hadiya Butt on 18/08/2023.
//

import SwiftUI

struct bestAcneProducts: View {
    var body: some View {
        ScrollView{
            
            VStack{
                
                Text("The Best Acne Products Of 2023, According to Dermatologists")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                
                Image("AcneProducts")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fit)
                
                Text("If you're tired of feeling bummed out every time a breakout occurs, and nothing in your bathroom cabinet seems to keep pimples at bay, you're not alone. Adult acne affects a significant percentage of people over the age of 25 — we're talking 40% to 54%. Every person's skin is different, and what works for your friend might not work for you. Plus, there's a myriad acne products out there claiming to curate your ideal acne skincare routine, whether you have hormonal acne to treat or need to get rid of gunky blackheads.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("Much like the breakout itself, it can be downright painful zeroing in on the very best products out there, so our editors vetted a list of the top acne treatments by speaking with eight board-certified dermatologists and aestheticians and the skincare pros in our Good Housekeeping Institute Beauty Lab. That includes acne face washes and benzoyl peroxide products that actively clear pores to expert-recommended sunscreens for acne that help protect your skin while you zap those zits and hero pimple patches to quickly put a stop to breakouts.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                Text("1")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best Rapid Acne Spot Treatment")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("Neutrogena Rapid Clear Stubborn Acne Spot Treatment Gel")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberOne")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("Shrink pimples stat with this speedy acne remedy. With more than 10,000 five-star reviews on Amazon, Neutrogena's gel-based formula boasts a potent 10% benzoyl peroxide concentration, which can significantly reduce pimple size and redness. As one satisfied customer noted, applying a small amount of the treatment before bedtime has yielded impressive results: 'I've been able to quickly eliminate pesky zits that I can feel forming overnight.' With strong gel treatments like this, make sure you moisturize as it can be drying.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("2")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
            }
            VStack{
                Text("Best Prescription-strength Retinoid For Acne")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("La Roche-Posay Effaclar Adapalene Gel")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
           
                Image("numberTwo")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                
                Text("This acne gel comes highly recommended by Beth Goldstein, M.D., a board-certified dermatologist and founder of Central Dermatology Center. It's a prescription-strength retinoid treatment that helps clear acne and prevents breakouts by increasing cell turnover and reducing pimple-exacerbating inflammation. Our GH pros deemed it one of the best treatments for hormonal acne. Lather on a good face SPF since retinoids can make skin sensitive to sun exposure.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                
                Text("3")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Affordable Moisturiser For Acne Prone Skin")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                
                Text("Cetaphil Face Moisturizer")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberThree")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("To keep your skin soft and supple after cleansing and applying serums, it's crucial to moisturize. Multiple dermatologists recommend Cetaphil's acne products, including its salicylic moisturizer, which can both clear acne and hydrate your skin. This product also contains prebiotics that may strengthen your skin barrier and protect it from damage or irritation. Although some reviewers appreciate its mattifying properties, others found that they needed to reapply for maximum hydration.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                Text("4")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
            }
            VStack{
                Text("Best Device For Acne")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("Dr Dennis Gross DRx SpectraLite Dpl FaceWare Pro")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberFour")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("Experts like dermatologist Shauna Diggs, M.D., suggest LED light therapy for blemish control. She recommends Dr. Dennis Gross Skincare's FDA-cleared LED face mask, a popular at-home beauty tool. This device uses blue light therapy to eliminate acne-causing bacteria and stimulate collagen production, resulting in a reduction of fine lines, wrinkles, rosacea and acne. Many users have reported significant improvements in their skin's appearance with consistent use of the device.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                Text("5")
                        .font(.largeTitle)
                        .fontWeight(.light)
                        .multilineTextAlignment(.center)
                        .padding(15)
                    Text("Best For Hormonal Acne")
                        .fontWeight(.light)
                        .multilineTextAlignment(.center)
                        .padding(15.0)
                Text("Peter Thomas Roth Goodbye Acne Complete Acne Treatment Gel")
                        .font(.largeTitle)
                        .fontWeight(.light)
                        .multilineTextAlignment(.center)
                        .padding(15)
                    Image("numberFive")
                        .resizable(resizingMode: .stretch)
                        .aspectRatio(contentMode: .fill)
                Text("When hormonal acne is triggered, this salicylic acid and retinol gel treatment steps in to calm harsh breakouts. Franzino used it to treat unusual acne around the mouth area. She said breakouts were less noticeable by the next morning and almost totally clear within a few days. It contains other skincare ingredients like vitamin C, peptides and aloe to treat skin holistically and help reduce inflammation that can come with blemishes. Keep in mind that some shoppers experienced a 'purge' period in which it got worse before it got better.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("6")
                        .font(.largeTitle)
                        .fontWeight(.light)
                        .multilineTextAlignment(.center)
                        .padding(15)
            }
            VStack{
                    Text("Affordable Adapalene Gel")
                        .fontWeight(.light)
                        .multilineTextAlignment(.center)
                        .padding(15.0)
                Text("Differrin Gel Acne Treatment")
                        .font(.largeTitle)
                        .fontWeight(.light)
                        .multilineTextAlignment(.center)
                        .padding(15)
                    
                    Image("numberSix")
                        .resizable(resizingMode: .stretch)
                        .aspectRatio(contentMode: .fill)
            
                Text("A popular retinoid treatment, Differin's acne gel is effective in treating troublesome breakouts, according to Tracy Evans M.D., M.P.H., a board-certified dermatologist and medical director of Pacific Skin and Cosmetic Dermatology. However, Dr. Evans warns that the gel can be drying and advises those with dry skin types to use it slowly, such as every third night after moisturizing. For a similar alternative, she suggests asking your dermatologist to prescribe Tretinoin (0.025-0.1%) in the appropriate strength for your skin.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("7")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best Acne Gel")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("CeraVe Salicylic Acid Acne Control Gel")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberSeven")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("A winner among dermatologists, CeraVe's powerful gel chases acne out of pores to welcome clear, healthy-looking skin. Its star ingredient salicylic acid is 'excellent for [getting rid of] excess oil,' as well as 'dissolving dead skin cells that clog the pores,' according to Renée Moran, M.D., owner of Dr. Renée Moran Medical Aesthetics and RM Skincare. Combine its powerful formula with a great moisturizer to restore any moisture loss, since some said it can be drying.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                Text("8")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
            }
            VStack{
                Text("Best Acne Spot Treatment")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("Kate Somerville EradiKate® Acne Treatment")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberEight")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("If you don't dig the smell of eggs, you probably don't want to put this all over your face. But, Wnek has used this fast-acting formula to treat stubborn pimples, and it definitely does the trick. Dip a cotton swab into the formula then apply directly on acne. The treatment goes on wet but firms like clay to dry up pimples. Made of zinc oxide, sulfur and salicylic acid, it effectively clears existing breakouts and absorbs oil. Just screw the lid on tight to ensure the liquid doesn't evaporate.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                Text("9")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best Face And Body Wash For Acne")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("PanOxyl Antimicrobial Acne Creamy Wash")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberNine")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("If your skin is on the oilier side, you may want to try a product that has benzoyl peroxide in it such as PanOxyl, according to Wong. Like salicylic acid, it helps to break up dead cells and excess oil, but it also works as an antiseptic that kills acne-causing bacteria. However, if you have dry or sensitive skin, benzoyl peroxide may be too harsh for you, even though PanOxyl claims that their wash is gentle.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                
                Text("10")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
            }
            VStack{
                Text("Best Acne Patches")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("Hero Cosmetics Mighty Patch The Original")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberTen")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("Sometimes getting rid of a blemish is as easy as slapping on a pimple patch, which ease pimples into releasing beneath cover. Once ready to peel off, the Mighty Patch's transparent material shows off the gunk and grime gathered at the scene of the crime, though they work best once a whitehead has formed. This one is virtually invisible so you can carry on with errands without paying any mind. Plus, the brand offers special shapes (like nose patches) if you're more prone to breakouts in certain areas.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("11")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best For Blackheads")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)

                Text("Caudalie Pore Minimizing Instant Detox Mask")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberEleven")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("Caudalie's blackhead mask is a one-step solution to minimize pores and mattify the complexion. GH experts love its potent blend of kaolin and bentonite, which work together to clear blackheads and absorb excess oil. Wnek, who has an oily skin type, confirms its effectiveness, saying her skin feels smoother and looks clearer after use. GH Beauty Director April Franzino raves that it provides an at-home facial experience that's comparable to a professional treatment. If you prefer non-scented masks, keep in mind that it has a subtle citrus scent.")
                    .fontWeight(.light)
                    .padding(15.0)
            }
            VStack{
                Text("12")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best For Dry, Sensitive Skin")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                Text("The Ordinary Niacinamide 10% + Zinc 1%")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberTwelve")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("Acne products for dry skin come few and far between since many can feel quite dehydrating. Sans fragrance and alcohol, The Ordinary's serum is made with acne-fighting niacinamide, an ingredient known to be compatible with sensitive skin types, to soothe inflammation and brighten and even out complexions. Just note to choose either vitamin C or niacinamide in your routine as both are potent ingredients.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("13")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Gentle Acne Facewash For Sensitive Skin")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)

            }
            VStack{
                Text("CeraVe Foaming Facial Cleanser")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberThirteen")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("CeraVe is a well-known over-the-counter brand that formulates products for various skin types. Jennifer Wong, PA-C, a dermatology physician's assistant at Advanced Dermatology PC, recommends their foaming wash because it's gentle and suitable for those with sensitive, acne-prone skin. It's a fragrance-free and non-comedogenic cleanser that effectively removes excess oil and dirt that could potentially clog pores. Designed for oil control, those with dry skin may need to opt for a different formula.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                Text("14")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best Face Wash")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                
                Text("Vichy Normaderm PhytoAction Daily Deep Cleansing Gel")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberFourteen")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("CeraVe is a well-known over-the-counter brand that formulates products for various skin types. Jennifer Wong, PA-C, a dermatology physician's assistant at Advanced Dermatology PC, recommends their foaming wash because it's gentle and suitable for those with sensitive, acne-prone skin. It's a fragrance-free and non-comedogenic cleanser that effectively removes excess oil and dirt that could potentially clog pores. Designed for oil control, those with dry skin may need to opt for a different formula.")
                    .fontWeight(.light)
                    .padding(15.0)
            }
            VStack{
                Text("15")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best For Sensitive Skin")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)

                Text("COSRX Advanced Snail 96 Mucin Power Essence")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberFifteen")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
            
                Text("It may not sound super appealing, but this snail mucin essence has gathered viral fame for its skin barrier-repairing reputation. Touted for boosting skin hydration and reducing skin inflammation, snail mucin helps remedy skin barrier damage. It's said to contain various skin-loving ingredients like hydrating hyaluronic acid, soothing allantoin (often found in toners for sensitive skin) and exfoliating glycolic acid. After using it for two weeks, one GH editor noticed a dramatic difference in taming breakouts. Other shoppers, however, wanted a more glassy effect.")
                    .fontWeight(.light)
                    .padding(15.0)
                
                
                Text("16")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best Sunscreen For Acne")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)
                
                Text("Supergoop! CC Screen")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Image("numberSixteen")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
            }
            VStack{
                Text("Ross loves Supergoop CC Screen because not only does it protect your skin from the sun with SPF 50, it 'has 20% zinc which is very high quality,' he says. Zinc is great for calming irritated skin, according to experts. This sunscreen is also a concealer so if you're looking for a moisturizing sunscreen that doubles as makeup, this product might be something you'll want to try. Oily skin types noted that it left a slight sheen so dust on a bit of powder to mattify.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                
                Text("17")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
                Text("Best Toner")
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15.0)

                Text("Paula's Choice CLEAR Regular Strength Anti-Redness Exfoliating Solution")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .multilineTextAlignment(.center)
                    .padding(15)
            
                Image("numberSeventeen")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                Text("Gently scrub away blackheads with Paula's Choice multi-tasking salicylic acid toner. The face exfoliator effectively deals with blackheads, minimizes breakouts and refines the appearance of pores without causing redness. This top-rated toner has received high praise from its users, including Wnek, for its ability to keep blackheads at bay while salicylic acid helps fight acne. However, those with eczema and rosacea should be cautious when using this toner as it contains acids that may irritate.")
                    .fontWeight(.light)
                    .padding(15.0)
            
                Text("The information and images in this article are taken from another article which you can find here https://www.goodhousekeeping.com/beauty/anti-aging/g37613134/best-acne-products-treatments/")
                    .font(.caption)
                    
                    
                    
                }
            }
        }
    
    struct bestAcneProducts_Previews: PreviewProvider {
        static var previews: some View {
            bestAcneProducts()
        }
    }
}
